language: node_js
node_js:
  - '5'
notifications:
  email:
    on_success: never
services:
  - docker
before_install:
  - docker build -t naaathan9 .
  - docker ps -a
after_success:
  - |-
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$HEROKU_EMAIL" -u="$HEROKU_USERNAME" -p="$HEROKU_PASSWORD" registry.heroku.com;
    docker build -t registry.heroku.com/naaathan9/web .;
    docker push registry.heroku.com/naaathan9/web;
    fi
